language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "pypy"
install:
    - pip install -r requirements.txt -r test-requirements.txt
script:
    py.test --cov=omx
after_success:
    coveralls
sudo: false
